	# Netlify configuration for React app deployment
	[build]
	  # Directory where the build command is run
	  base = "reactproject2"
	  
	  # Build command - install dependencies first, then build
	  command = "npm install && npm run build"
	  
	  # Directory that contains the deploy-ready HTML files and assets
	  publish = "build"
	
	# Redirect all traffic to index.html for client-side routing
	# This ensures React Router works correctly on page refresh
	[[redirects]]
	  from = "/*"
	  to = "/index.html"
  status = 200